services:
  - type: web
    name: spendwise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
